module.exports = {
  // General stuff
  BOT_ERROR: 'Action Failed',

  // command stuff
  COMMAND_DISABLED: 'This command is currently disabled.',
  COMMAND_DISABLED_FOR_TEST: 'This command is currently disabled for testing!',
  COMMAND_ERROR: 'One of my developers made an error while coding this command! Don\'t worry, the error is not on your side. Please contact <@207471947662098432>, <@473860522710794250> or <@173336582265241601>',
  COMMAND_MAINTENANCE: 'I\'m currently in maintenance, please try again later.',
  COMMAND_NO_ARGUMENTS_GIVEN: 'You did not provide any arguments.',
  COMMAND_NOT_ENOUGH_ARGUMENTS_GIVEN: 'You did not provide enough arguments.',
  COMMAND_NO_PERMISSION: 'You don\'t have the permission to do that.',
  COMMAND_PROVIDE_VALID_TAG: 'Please provide a user tag.',
  COMMAND_PROVIDE_A_NUMBER: 'Please provide a number.',
  COMMAND_WRONG_ARGUMENTS_GIVEN: 'You did not provide valid arguments.',
  CANT_EXECUTE_IN_DMS: 'I can\'t execute this command inside DM\'s!',
  COMMAND_NOIDONTTHINKIWILL_LMAO: 'https://tenor.com/view/no-i-dont-think-i-will-captain-america-old-capt-gif-17162888',
  COMMAND_NOT_A_NUMBER: 'The amount parameter isn\'t a number.',
  COMMAND_USER_DOESNT_EXIST: 'This user doesn\'t exist.',
  COMMAND_NO_IMAGE_FOUND: 'No image found in 10 previous messages.',
  COMMAND_MESSAGE_IMAGE_NOT_ATTACHED: 'This message does not have any image attached.',
  COMMAND_ID_IMAGE_NOT_ATTACHED: 'This ID does not have any image attached.',
  COMMAND_INVALID_EXTENSION: 'Image extension is not supported',
  COMMAND_URL_ONLY_SAME_CHANNEL: 'The message URL needs to be from the same channel. Don\'t ask why, I don\'t know myself.',
  COMMAND_SEARCHING_FOR_TEXTURE: 'Searching for your texture, please wait...',
  COMMAND_TOO_MUCH_ARGS_GIVEN: 'Too much arguments were given!',

  // Help descriptions for commands
  HELP_DESC_AUTOPUSH: 'Use this command to push textures from #results to GitHub.',
  HELP_DESC_BAN: 'Ban a user from the current Discord server',
  HELP_DESC_CLEAR: 'Clear messages in a channel',
  HELP_DESC_EMBED: 'Modify an embed',
  HELP_DESC_PUSH: 'Push file to GitHub & update the contributor list.',

  HELP_DESC_BEHAVE: '(⌯˃̶᷄ ﹏ ˂̶᷄⌯)',
  HELP_DESC_HOTFIX: 'Fix something, may change at anytime',
  HELP_DESC_INFOEMBED: 'Posts specific embeds for the info channel categories on the Compliance servers.',
  HELP_DESC_PING: 'Pong!',
  HELP_DESC_RELOAD: 'Reloads a command',
  HELP_DESC_RESTART: 'Pulls modifications and restart the bot',
  HELP_DESC_SAY: 'Make the bot send any message you specify',
  HELP_DESC_SHUTDOWN: 'Stops the bot',
  HELP_DESC_STATUS: 'Changes the bot\'s status: \n**Activity**:\nPLAYING, STREAMING, LISTENING, WATCHING, COMPETING, CUSTOM_STATUS (does not work)\n**Presence**:\nonline, idle, dnd',

  HELP_DESC_BEAN: 'get B E A N E D',
  HELP_DESC_MUTE: 'Mute someone',
  HELP_DESC_RULES: 'Creates rules embed.',
  HELP_DESC_SLOWMODE: 'Enable or disable the slowmode in a channel',
  HELP_DESC_UNMUTE: 'Unmute someone',
  HELP_DESC_WARN: 'Warn someone',

  HELP_DESC_ABOUT: 'Displays a texture that you or someone else made',
  HELP_DESC_ANIMATE: 'Animates a texture.',
  HELP_DESC_BALL: 'Asks a question to the 8-ball.',
  HELP_DESC_BOB: 'Spongebobifies a text.',
  HELP_DESC_CHARSHIFT: 'Encodes with Caesar shift with given offset.',
  HELP_DESC_COIN: 'Flips a coin.',
  HELP_DESC_COLOR: 'Use this command to show information about a color.',
  HELP_DESC_COMPARE: 'Allows vanilla / pack comparaison side by side',
  HELP_DESC_FEEDBACK: 'Suggest things or report bugs directly to the bot devs.',
  HELP_DESC_GUIDELINES: 'Shows the texturing guidelines of Compliance 32x.',
  HELP_DESC_HELP: 'Show help for a specified command.',
  HELP_DESC_INFO: 'Displays some info about the bot in your DMs.',
  HELP_DESC_KILL: 'Shows a minecraft death message.',
  HELP_DESC_LOVE: 'Shows the love for someone else.',
  HELP_DESC_MAGNIFY: 'Resize an image,\nImage URL needs to end with ``.png``, ``.jpeg/jpg`` or ``.gif``,\nMessage ID needs to be from the same channel.\nMagnify only the first frame of a GIF',
  HELP_DESC_MISSING: 'Shows tree view of missing textures for a particular edition',
  HELP_DESC_MODPING: 'Tag online mods to call for help.',
  HELP_DESC_MODTOOLS: 'Displays tools for Minecraft Dungeons modding.',
  HELP_DESC_NAMESEARCH: 'Searches names through guild members.',
  HELP_DESC_ORDER: 'Order something',
  HELP_DESC_PALETTE: 'Get the colours of an image,\nImage URL needs to end with ``.png``, ``.jpeg/jpg`` or ``.gif``,\nMessage ID needs to be from the same channel.\nGIF: Return the palette of the first frame only',
  HELP_DESC_POLL: 'Make a poll to ask people!',
  HELP_DESC_PROFILE: 'Add personal information for the Compliance Website Gallery.',
  HELP_DESC_QUOTE: 'Gives inspirational quote.',
  HELP_DESC_SKIN: 'Get the skin of a Minecraft Player.',
  HELP_DESC_STATS: 'Displays various stats of the bot.',
  HELP_DESC_TEXTURE: 'Displays a specified texture from either vanilla Minecraft or Compliance.\nYou can search for a texture name, or use ``_`` at the beginning to search for non-complete names (such as _sword).\nYou can also use ``/`` at the begining to specify a folder instead of a texture name.',
  HELP_DESC_TILE: 'Tile an image, if no arguments are given, a grid shape is selected by default. The bot searches the last 10 messages for an image.\nGIF: only works with the first frame.',
  HELP_DESC_TRANSLATE: 'Translates messages to the selected language.',
  HELP_DESC_WEBSITE: 'Displays website for the given keyword, see examples for keywords.',
  HELP_DESC_MCWIKI: 'Searches official Minecraft wiki',

  // animate function
  INPUT_TOO_BIG: 'The input picture is too big!',
  INPUT_TOO_WIDE: 'The input picture is too wide!',
  CANT_ANIMATE: 'This texture can\'t be animated.',

  // command uses
  COMMAND_USES_ANYONE: 'Anyone',
  COMMAND_USES_ANYONE_DUNGEONS: 'Anyone on Compliance Dungeons Discord',
  COMMAND_USES_DEVS: 'Bot Developers',
  COMMAND_USES_ADMINS: 'Administrators',
  COMMAND_USES_MODS: 'Moderators',
  COMMAND_USES_DISABLED: 'Nobody (disabled)',

  BALL_RESPONSES: [
    "Well... yeah. It's kinda obvious.",
    "Sure, I guess.",
    "uhm... duh??",
    "How could I ever say no to you? :heart:",
    "Ye.",
    "Very, very likely",
    "I'm betting my life on it",
    "Yup yup",
    "Maybe. Perhaps. I guess.",
    "Yes. Well, yes *and* no.",
    "No. Well, yes *and* no.",
    "Just... I mean, if you want to?",
    "I suppose. It's not the first thing that comes to my mind though",
    "I *GUESS*",
    "I don't know, maybe?",
    "It's not *impossible*, it's just not likely.",
    "NO! NEVER!",
    "Uhm... I don't think so",
    "Yeah, no, definitely not.",
    "Not. A. Chance.",
    "No.",
    "GOD NO",
    "I am certain that is not the case, no.",
    "Oh, no no no no no. Just no.",
    "Ehh...",
    "I'm kinda busy here, can't you figure it out yourself?",
    "I don't think I wanna give my opinion on this.",
    "LEAVE ME ALONE REEEEEEE",
    "It Depends™",
    "On times like this, I like to ask myself: what would Jesus say?",
    "Great question. Just wonderful. I love it. Ask me again.",
    "Huh. Never thought of it that way. I'll sleep on it and get back to you tomorrow, 'k?",
    "Well... yeah. It's kinda obvious.",
    "Sure, I guess.",
    "uhm... duh??",
    "How could I ever say no to you? :heart:",
    "Ye.",
    "Very, very likely",
    "I'm betting my life on it",
    "Yup yup",
    "Maybe. Perhaps. I guess.",
    "Yes. Well, yes *and* no.",
    "No. Well, yes *and* no.",
    "Just... I mean, if you want to?",
    "I suppose. It's not the first thing that comes to my mind though",
    "I *GUESS*",
    "I don't know, maybe?",
    "It's not *impossible*, it's just not likely.",
    "NO! NEVER!",
    "Uhm... I don't think so",
    "Yeah, no, definitely not.",
    "Not. A. Chance.",
    "No.",
    "GOD NO",
    "I am certain that is not the case, no.",
    "Oh, no no no no no. Just no.",
    "Ehh...",
    "I'm kinda busy here, can't you figure it out yourself?",
    "I don't think I wanna give my opinion on this.",
    "LEAVE ME ALONE REEEEEEE",
    "It Depends™",
    "On times like this, I like to ask myself: what would Jesus say?",
    "Great question. Just wonderful. I love it. Ask me again.",
    "Huh. Never thought of it that way. I'll sleep on it and get back to you tomorrow, 'k?"
  ],

  // bean command
  BEAN_CANT_BEAN_SELF: 'You can\'t bean yourself!',
  BEAN_SPECIFY_USER: 'You need to specify a user to bean!',

  // behave command
  BEHAVE_ANSWER: 'I\'m so sorry! (⌯˃̶᷄ ﹏ ˂̶᷄⌯)',

  // say command
  SAY_NOT_SPECIFIED: 'You haven\'t specified a message to send.',

  // ban command
  BAN_CANT_BAN_SELF: 'You can\'t ban yourself!',
  BAN_SPECIFY_USER: 'You need to specify a user to ban!',
  BAN_BOT_NO_PERMISSION: 'I don\'t have enough permissions to ban users! Please enable the ban permission for my role.',
  BAN_NOT_BANNABLE: 'This user is not able to be banned!',

  KILL_SPECIFY_USER: 'You need to specify a user to kill!',
  KILL_WEAPON_RESPONSE: '%player% was killed by %weapon%',
  KILL_RESPONSES: [
    '%player% was pricked to death',
    '%player% starved to death',
    '%player% died from dehydration',
    '%player% drowned',
    '%player% blew up',
    '%player% was killed by [Intentional Game Design]',
    '%player% hit the ground too hard',
    '%player% fell from a high place',
    '%player% fell off some vines',
    '%player% fell off some weeping vines',
    '%player% fell off some twisting vines',
    '%player% fell off scaffolding',
    '%player% fell while climbing',
    '%player% was impaled on a stalagmite',
    '%player% was squashed by a falling anvil',
    '%player% was squashed by a falling block',
    '%player% was skewered by a falling stalactite',
    '%player% went up in flames',
    '%player% burned to death',
    '%player% went off with a bang',
    '%player% tried to swim in lava',
    '%player% was struck by lightning',
    '%player% discovered the floor was lava',
    '%player% was killed by magic',
    '%player% froze to death',
    '%player% was stung to death',
    '%player% suffocated in a wall',
    '%player% was squished too much',
    '%player% was poked to death by a sweet berry bush',
    '%player% fell out of the world',
    '%player% withered away',
    '%player% died',
  ],

  LOVE_TWO_USERS: 'You need 2 users as lovers!',

  // mute command
  MUTE_NOT_VALID_TIME: 'You did\'t specify a valid time.',
  MUTE_SPECIFY_USER: 'You need to specify a user to mute.',
  MUTE_CANT_MUTE_SELF: 'You can\'t mute yourself!',
  MUTE_SPECIFY_INTEGER: 'You have to specify an integer.'
}