name: Feature request
description: Suggest an idea
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the feature you'd like
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot(s)
      description: If you have done any concepts, feel free to add them here
    validations:
      required: false
  - type: textarea
    attributes:
      label: Notes
      description: Add any other context about the request that doesn't fit into any category here
    validations:
      required: false