name: LanguageGeneration

on:
    push:
        branches: [typescript]
        paths: 
          - "lang/**"
          - "src/**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSH }}
                  script: |
                      cd ./"CompliBot (TS)"
                      git stash
                      git pull
                      npm run genLang
                      git add lang/README.md
                      git commit -m "Language readme updated"
                      git push